version: '3.8'
services:
  catalog-service:
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - 9001:9001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testdata
    networks:
      - catalog-network

networks:
  catalog-network:
    name: catalog-network
    external: true
